/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metodos.numericos;

import org.math.plot.Plot2DPanel;
/**
 *
 * @author Tecno Data
 */
public class Graficadora extends javax.swing.JFrame {

    /**
     * Creates new form Graficadora
     */
    public Graficadora() {
        initComponents();
        grafica.setBounds(570, 10, 390, 300);
        add(grafica);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDatos = new javax.swing.JLabel();
        lblFuncion = new javax.swing.JLabel();
        txtFuncion = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lblParametros = new javax.swing.JLabel();
        lblX1 = new javax.swing.JLabel();
        txtX1 = new javax.swing.JTextField();
        lblX2 = new javax.swing.JLabel();
        txtX2 = new javax.swing.JTextField();
        lblRaiz = new javax.swing.JLabel();
        txtRaiz = new javax.swing.JTextField();
        lblError = new javax.swing.JLabel();
        txtError = new javax.swing.JTextField();
        lblMax = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDatos.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblDatos.setText("INGRESE DATOS:");

        lblFuncion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblFuncion.setText("f(x)=");

        txtFuncion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        btnCalcular.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblParametros.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblParametros.setText("INGRESE PARAMETROS: ");

        lblX1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblX1.setText("X1=");

        txtX1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblX2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblX2.setText("X2=");

        txtX2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblRaiz.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        lblRaiz.setText("Raiz: ");

        txtRaiz.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtRaiz.setEnabled(false);

        lblError.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblError.setText("Error: ");

        txtError.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtError.setEnabled(false);

        lblMax.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblMax.setText("Maximo:");

        txtMax.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(85, 85, 85)
                            .addComponent(lblFuncion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblParametros)
                                .addComponent(lblDatos))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblX1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtX1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblX2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRaiz)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtRaiz))
                                    .addComponent(txtX2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblError)
                            .addGap(18, 18, 18)
                            .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblMax)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtMax)))
                    .addComponent(btnCalcular))
                .addContainerGap(461, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDatos)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFuncion)
                            .addComponent(txtFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(lblParametros)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblError)
                            .addComponent(txtError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblX1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblX2)
                    .addComponent(txtX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMax)
                    .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaiz)
                    .addComponent(txtRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcular))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        String def =txtFuncion.getText();
        
        double X1=Double.parseDouble(lblX1.getText());
        double X2=Double.parseDouble(lblX2.getText());
        double error=Double.parseDouble(lblError.getText());
        int max=Integer.parseInt(lblMax.getText());
        X1=0;
        X2=0;
        Funcion ff=new Funcion (def);
        Metodo s= new Metodo ();
        double r=s.raiz(ff, X1, X2, max, error);
        lblRaiz.setText(""+r);
        
        double [] x=new double [200];
        double [] y=new double [200];
        double Xi=X1-10;
        for (int i=0; i<200;i++){
            x[i]=Xi+i*0.1;
            y[i]=ff.evaluar(x[i]);
        }
        
        grafica.addLegend("SOUTH");
        grafica.removeAllPlots();
        grafica.addLinePlot(def,x, y);
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graficadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graficadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graficadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graficadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graficadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lblDatos;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblFuncion;
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblParametros;
    private javax.swing.JLabel lblRaiz;
    private javax.swing.JLabel lblX1;
    private javax.swing.JLabel lblX2;
    private javax.swing.JTextField txtError;
    private javax.swing.JTextField txtFuncion;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtRaiz;
    private javax.swing.JTextField txtX1;
    private javax.swing.JTextField txtX2;
    // End of variables declaration//GEN-END:variables
Plot2DPanel grafica =new Plot2DPanel();
}
